version: '2'
services:
  akhq:
    image: tchiotludo/akhq:0.14.1
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - 11817:8080
